image: alpine:latest

pages:
    stage: deploy
    script:
        - mkdir public
        - cp -rf index.html public/ 2>/dev/null
        - cp -rf js public/ 2>/dev/null
        - cp -rf css public/ 2>/dev/null
        - cp -rf img public/ 2>/dev/null
    artifacts:
        paths:
            - public
    only:
        - master
