image: alpine:latest

pages:
    stage: deploy
    script:
        - mkdir public
        - cp -r ./{index.html,img,js,css} public/
    artifacts:
        paths:
            - public
    only:
        - master
