image: alpine:latest

pages:
    stage: deploy
    script:
        - mkdir public
        - cp -rf ./{index.html,img,js,css} public/ 2>/dev/null
    artifacts:
        paths:
            - public
    only:
        - master
