image: alpine:latest

pages:
    stage: deploy
    script:
        - mkdir -p public
        - cp -rf index.html public/index.html
        - cp -rf js public/js
        - cp -rf css public/css
        - cp -rf img public/img
    artifacts:
        paths:
            - public
    only:
        - master
